---
name: vale

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: false
          files: '["docs/guide"]'
          filter_mode: nofilter
          reporter: github-check
